name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: |
        npm ci
        npm run build
        node_modules/.bin/gh-pages -d dist --user "Nikita Kirsanov <kitos.kirsanov@gmail.com>" --repo https://${{ secrets.GH_TOKEN }}@github.com/kitos/game-of-life.git
